# Military Power Clustering Project
-World military power
Source : globalfirepower.com on 1st may 2020

- https://data.world/vizzup/world-military-power/workspace/file?filename=World+military+power.xlsx

# Import Libraries

In [212]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
%matplotlib inline
pd.set_option("display.max_columns", 200)
pd.set_option("display.max_rows", 150)

# Ingest Data

In [222]:
df = pd.read_excel("World military power.xlsx", header=[0, 1])
df.head()

       2020 ranking                               Airforce Strength  \
  Military Strength Military Strength Power Index Aircraft Strength
0       Afghanistan                        1.3444       Afghanistan
1           Albania                        2.3137           Albania
2           Algeria                        0.4659           Algeria
3            Angola                        0.8379            Angola
4         Argentina                        0.6521         Argentina

                                                        \
  Aircraft Strength value Fighter/Interceptor Strength
0                     260                  Afghanistan
1                      19                      Albania
2                     551                      Algeria
3                     295                       Angola
4                     227                    Argentina

                                                               \
  Fighter/Interceptor Strength value Attack Aircraft Strength
0                                  0              Afghanistan
1                                  0                  Albania
2                                103                  Algeria
3                                 72                   Angola
4                                 24                Argentina

                                                                    \
  Attack Aircraft Strength value Transport Aircraft Fleet Strength
0                             25                       Afghanistan
1                              0                           Albania
2                             22                           Algeria
3                             18                            Angola
4                              7                         Argentina

                                                                  \
  Transport Aircraft Fleet Strength value Trainer Aircraft Fleet
0                                      30            Afghanistan
1                                       0                Albania
2                                      59                Algeria
3                                      30                 Angola
4                                       9              Argentina

                                                          \
  Trainer Aircraft Fleet value Helicopter Fleet Strength
0                            0               Afghanistan
1                            0                   Albania
2                           87                   Algeria
3                           47                    Angola
4                           64                 Argentina

                                                                    \
  Helicopter Fleet Strength value Attack Helicopter Fleet Strength
0                             187                      Afghanistan
1                              19                          Albania
2                             257                          Algeria
3                             126                           Angola
4                             100                        Argentina

                                         Land Strength                      \
  Attack Helicopter Fleet Strength value Tank Strength Tank Strength value
0                                      0   Afghanistan                   0
1                                      0       Albania                   0
2                                     45       Algeria                 880
3                                     15        Angola                 379
4                                      0     Argentina                 370

                                                                             \
  AFV/APC Strength AFV/APC Strength value Self-Propelled Artillery Strength
0      Afghanistan                   1062                       Afghanistan
1          Albania                    467                           Albania
2          Algeria                   7361                           Algeria
3           Angola                    595                            Angola
4        Argentina                    739                         Argentina

                                                                    \
  Self-Propelled Artillery Strength value Towed Artillery Strength
0                                       0              Afghanistan
1                                       0                  Albania
2                                     320                  Algeria
3                                      28                   Angola
4                                      83                Argentina

                                                            \
  Towed Artillery Strength value Rocket Projector Strength
0                            176               Afghanistan
1                              0                   Albania
2                            240                   Algeria
3                            357                    Angola
4                            172                 Argentina

                                         Navy Strength  \
  Rocket Projector Strength value Navy Fleet Strengths
0                              50          Afghanistan
1                               0              Albania
2                             316              Algeria
3                             115               Angola
4                              26            Argentina

                                                              \
  Navy Fleet Strengths value Aircraft Carrier Fleet Strength
0                        0.0                     Afghanistan
1                       38.0                         Albania
2                      201.0                         Algeria
3                       57.0                          Angola
4                       49.0                       Argentina

                                                                  \
  Aircraft Carrier Fleet Strength value Submarine Fleet Strength
0                                   0.0              Afghanistan
1                                   0.0                  Albania
2                                   0.0                  Algeria
3                                   0.0                   Angola
4                                   0.0                Argentina

                                                           \
  Submarine Fleet Strength value Destroyer Fleet Strength
0                            0.0              Afghanistan
1                            0.0                  Albania
2                            6.0                  Algeria
3                            0.0                   Angola
4                            2.0                Argentina

                                                         \
  Destroyer Fleet Strength value Frigate Fleet Strength
0                            0.0            Afghanistan
1                            0.0                Albania
2                            0.0                Algeria
3                            0.0                 Angola
4                            4.0              Argentina

                                              Finances  \
  Frigate Fleet Strength value defense spending budget
0                          0.0             Afghanistan
1                          0.0                 Albania
2                          5.0                 Algeria
3                          0.0                  Angola
4                          0.0               Argentina

                                                                   \
  defense spending budget value External Debt External Debt value
0               12,00,00,00,000   Afghanistan      2,84,00,00,000
1                  25,00,00,000       Albania      9,50,50,00,000
2               13,00,00,00,000       Algeria      6,26,00,00,000
3                7,00,00,00,000        Angola     42,08,00,00,000
4                4,20,00,00,000     Argentina   2,14,90,00,00,000

       Logistics                      Natural resources                       \
  Airport Totals Airport Totals value    Oil Production Oil Production value
0    Afghanistan                   43       Afghanistan                    0
1        Albania                    4           Albania                16000
2        Algeria                  157           Algeria            13,06,000
3         Angola                  176            Angola            16,66,000
4      Argentina                 1138         Argentina             4,79,400

                                                             \
  Oil Consumption Oil Consumption value Proven Oil Reserves
0     Afghanistan                  5500         Afghanistan
1         Albania                 42500             Albania
2         Algeria              3,25,000             Algeria
3          Angola                 82300              Angola
4       Argentina              6,85,000           Argentina

                                      Manpower                           \
  Proven Oil Reserves value Available Manpower Available Manpower value
0                         0        Afghanistan              1,43,25,743
1              16,83,00,000            Albania                15,19,438
2           12,20,00,00,000            Algeria              2,07,41,263
3            8,27,30,00,000             Angola                62,44,205
4            2,18,50,00,000          Argentina              2,01,79,430

                                                       Geography  \
  Total Population Total Population value Total Square Land Area
0      Afghanistan            3,49,40,837            Afghanistan
1          Albania              30,57,220                Albania
2          Algeria            4,16,57,488                Algeria
3           Angola            3,03,55,880                 Angola
4        Argentina            4,46,94,198              Argentina

                                                         \
  Total Square Land Area value Total Coastline Coverage
0                     6,52,230              Afghanistan
1                        28748                  Albania
2                    23,81,741                  Algeria
3                    12,46,700                   Angola
4                    27,80,400                Argentina

                                                          \
  Total Coastline Coverage value Total Waterway Coverage
0                              0             Afghanistan
1                            362                 Albania
2                            998                 Algeria
3                           1600                  Angola
4                           4989               Argentina

                                                       \
  Total Waterway Coverage value Total Border Coverage
0                          1200           Afghanistan
1                            41               Albania
2                             0               Algeria
3                          1300                Angola
4                         11000             Argentina


  Total Border Coverage value
0                      5987.0
1                       691.0
2                      6734.0
3                      5369.0
4                     11968.0

# EDA

## Implement basic steps to see how is your data looks like

In [223]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 138 entries, 0 to 137
Data columns (total 60 columns):
 #   Column                                                        Non-Null Count  Dtype
---  ------                                                        --------------  -----
 0   (2020 ranking, Military Strength)                             138 non-null    object
 1   (2020 ranking, Military Strength Power Index)                 138 non-null    float64
 2   (Airforce Strength, Aircraft Strength)                        138 non-null    object
 3   (Airforce Strength, Aircraft Strength value)                  138 non-null    int64
 4   (Airforce Strength, Fighter/Interceptor Strength)             138 non-null    object
 5   (Airforce Strength, Fighter/Interceptor Strength value)       138 non-null    int64
 6   (Airforce Strength, Attack Aircraft Strength)                 138 non-null    object
 7   (Airforce Strength, Attack Aircraft Strength value)           138 non-null    int64
 8   (Airforce Strength, Transport Aircraft Fleet Strength)        138 non-null    object
 9   (Airforce Strength, Transport Aircraft Fleet Strength value)  138 non-null    int64
 10  (Airforce Strength, Trainer Aircraft Fleet)                   138 non-null    object
 11  (Airforce Strength, Trainer Aircraft Fleet value)             138 non-null    int64
 12  (Airforce Strength, Helicopter Fleet Strength)                138 non-null    object
 13  (Airforce Strength, Helicopter Fleet Strength value)          138 non-null    int64
 14  (Airforce Strength, Attack Helicopter Fleet Strength)         138 non-null    object
 15  (Airforce Strength, Attack Helicopter Fleet Strength value)   138 non-null    int64
 16  (Land Strength, Tank Strength)                                138 non-null    object
 17  (Land Strength, Tank Strength value)                          138 non-null    int64
 18  (Land Strength, AFV/APC Strength)                             138 non-null    object
 19  (Land Strength, AFV/APC Strength value)                       138 non-null    int64
 20  (Land Strength, Self-Propelled Artillery Strength)            138 non-null    object
 21  (Land Strength, Self-Propelled Artillery Strength value)      138 non-null    int64
 22  (Land Strength, Towed Artillery Strength)                     138 non-null    object
 23  (Land Strength, Towed Artillery Strength value)               138 non-null    int64
 24  (Land Strength, Rocket Projector Strength)                    138 non-null    object
 25  (Land Strength, Rocket Projector Strength value)              138 non-null    int64
 26  (Navy Strength, Navy Fleet Strengths)                         124 non-null    object
 27  (Navy Strength, Navy Fleet Strengths value)                   124 non-null    float64
 28  (Navy Strength, Aircraft Carrier Fleet Strength)              115 non-null    object
 29  (Navy Strength, Aircraft Carrier Fleet Strength value)        115 non-null    float64
 30  (Navy Strength, Submarine Fleet Strength)                     115 non-null    object
 31  (Navy Strength, Submarine Fleet Strength value)               115 non-null    float64
 32  (Navy Strength, Destroyer Fleet Strength)                     115 non-null    object
 33  (Navy Strength, Destroyer Fleet Strength value)               115 non-null    float64
 34  (Navy Strength, Frigate Fleet Strength)                       115 non-null    object
 35  (Navy Strength, Frigate Fleet Strength value)                 115 non-null    float64
 36  (Finances, defense spending budget)                           138 non-null    object
 37  (Finances, defense spending budget value)                     138 non-null    object
 38  (Finances, External Debt)                                     138 non-null    object
 39  (Finances, External Debt value)                               138 non-null    object
 40  (Logistics, Airport Totals)                                   138 non-null    object
 41  (Logistics, Airport Totals value)                             138 non-null    int64
 42  (Natural resources, Oil Production)                           138 non-null    object
 43  (Natural resources, Oil Production value)                     138 non-null    object
 44  (Natural resources, Oil Consumption)                          138 non-null    object
 45  (Natural resources, Oil Consumption value)                    138 non-null    object
 46  (Natural resources, Proven Oil Reserves)                      138 non-null    object
 47  (Natural resources, Proven Oil Reserves value)                138 non-null    object
 48  (Manpower, Available Manpower)                                138 non-null    object
 49  (Manpower, Available Manpower value)                          138 non-null    object
 50  (Manpower, Total Population)                                  138 non-null    object
 51  (Manpower, Total Population value)                            138 non-null    object
 52  (Geography, Total Square Land Area)                           138 non-null    object
 53  (Geography, Total Square Land Area value)                     138 non-null    object
 54  (Geography, Total Coastline Coverage)                         109 non-null    object
 55  (Geography, Total Coastline Coverage value)                   109 non-null    object
 56  (Geography, Total Waterway Coverage)                          138 non-null    object
 57  (Geography, Total Waterway Coverage value)                    138 non-null    object
 58  (Geography, Total Border Coverage)                            129 non-null    object
 59  (Geography, Total Border Coverage value)                      129 non-null    float64
dtypes: float64(7), int64(13), object(40)
memory usage: 64.8+ KB

In [224]:
df.shape

(138, 60)

In [245]:
df.duplicated().sum()

0

In [226]:
df.isnull().sum()

2020 ranking       Military Strength                           0
                   Military Strength Power Index               0
Airforce Strength  Aircraft Strength                           0
                   Aircraft Strength value                     0
                   Fighter/Interceptor Strength                0
                   Fighter/Interceptor Strength value          0
                   Attack Aircraft Strength                    0
                   Attack Aircraft Strength value              0
                   Transport Aircraft Fleet Strength           0
                   Transport Aircraft Fleet Strength value     0
                   Trainer Aircraft Fleet                      0
                   Trainer Aircraft Fleet value                0
                   Helicopter Fleet Strength                   0
                   Helicopter Fleet Strength value             0
                   Attack Helicopter Fleet Strength            0
                   Attack Helicopter Fleet Strength value      0
Land Strength      Tank Strength                               0
                   Tank Strength value                         0
                   AFV/APC Strength                            0
                   AFV/APC Strength value                      0
                   Self-Propelled Artillery Strength           0
                   Self-Propelled Artillery Strength value     0
                   Towed Artillery Strength                    0
                   Towed Artillery Strength value              0
                   Rocket Projector Strength                   0
                   Rocket Projector Strength value             0
Navy Strength      Navy Fleet Strengths                       14
                   Navy Fleet Strengths value                 14
                   Aircraft Carrier Fleet Strength            23
                   Aircraft Carrier Fleet Strength value      23
                   Submarine Fleet Strength                   23
                   Submarine Fleet Strength value             23
                   Destroyer Fleet Strength                   23
                   Destroyer Fleet Strength value             23
                   Frigate Fleet Strength                     23
                   Frigate Fleet Strength value               23
Finances           defense spending budget                     0
                   defense spending budget value               0
                   External Debt                               0
                   External Debt value                         0
Logistics          Airport Totals                              0
                   Airport Totals value                        0
Natural resources  Oil Production                              0
                   Oil Production value                        0
                   Oil Consumption                             0
                   Oil Consumption value                       0
                   Proven Oil Reserves                         0
                   Proven Oil Reserves value                   0
Manpower           Available Manpower                          0
                   Available Manpower value                    0
                   Total Population                            0
                   Total Population value                      0
Geography          Total Square Land Area                      0
                   Total Square Land Area value                0
                   Total Coastline Coverage                   29
                   Total Coastline Coverage value             29
                   Total Waterway Coverage                     0
                   Total Waterway Coverage value               0
                   Total Border Coverage                       9
                   Total Border Coverage value                 9
dtype: int64

## Convert multi index columns to one level

In [231]:
df.columns.values

array([('2020 ranking', 'Military Strength'),
       ('2020 ranking', 'Military Strength Power Index'),
       ('Airforce Strength', 'Aircraft Strength'),
       ('Airforce Strength', 'Aircraft Strength value'),
       ('Airforce Strength', 'Fighter/Interceptor Strength'),
       ('Airforce Strength', 'Fighter/Interceptor Strength value'),
       ('Airforce Strength', 'Attack Aircraft Strength'),
       ('Airforce Strength', 'Attack Aircraft Strength value'),
       ('Airforce Strength', 'Transport Aircraft Fleet Strength'),
       ('Airforce Strength', 'Transport Aircraft Fleet Strength value'),
       ('Airforce Strength', 'Trainer Aircraft Fleet'),
       ('Airforce Strength', 'Trainer Aircraft Fleet value'),
       ('Airforce Strength', 'Helicopter Fleet Strength'),
       ('Airforce Strength', 'Helicopter Fleet Strength value'),
       ('Airforce Strength', 'Attack Helicopter Fleet Strength'),
       ('Airforce Strength', 'Attack Helicopter Fleet Strength value'),
       ('Land Strength', 'Tank Strength'),
       ('Land Strength', 'Tank Strength value'),
       ('Land Strength', 'AFV/APC Strength'),
       ('Land Strength', 'AFV/APC Strength value'),
       ('Land Strength', 'Self-Propelled Artillery Strength'),
       ('Land Strength', 'Self-Propelled Artillery Strength value'),
       ('Land Strength', 'Towed Artillery Strength'),
       ('Land Strength', 'Towed Artillery Strength value'),
       ('Land Strength', 'Rocket Projector Strength'),
       ('Land Strength', 'Rocket Projector Strength value'),
       ('Navy Strength', 'Navy Fleet Strengths'),
       ('Navy Strength', 'Navy Fleet Strengths value'),
       ('Navy Strength', 'Aircraft Carrier Fleet Strength'),
       ('Navy Strength', 'Aircraft Carrier Fleet Strength value'),
       ('Navy Strength', 'Submarine Fleet Strength'),
       ('Navy Strength', 'Submarine Fleet Strength value'),
       ('Navy Strength', 'Destroyer Fleet Strength'),
       ('Navy Strength', 'Destroyer Fleet Strength value'),
       ('Navy Strength', 'Frigate Fleet Strength'),
       ('Navy Strength', 'Frigate Fleet Strength value'),
       ('Finances', 'defense spending budget'),
       ('Finances', 'defense spending budget value'),
       ('Finances', 'External Debt'), ('Finances', 'External Debt value'),
       ('Logistics', 'Airport Totals'),
       ('Logistics', 'Airport Totals value'),
       ('Natural resources', 'Oil Production'),
       ('Natural resources', 'Oil Production value'),
       ('Natural resources', 'Oil Consumption'),
       ('Natural resources', 'Oil Consumption value'),
       ('Natural resources', 'Proven Oil Reserves'),
       ('Natural resources', 'Proven Oil Reserves value'),
       ('Manpower', 'Available Manpower'),
       ('Manpower', 'Available Manpower value'),
       ('Manpower', 'Total Population'),
       ('Manpower', 'Total Population value'),
       ('Geography', 'Total Square Land Area'),
       ('Geography', 'Total Square Land Area value'),
       ('Geography', 'Total Coastline Coverage'),
       ('Geography', 'Total Coastline Coverage value'),
       ('Geography', 'Total Waterway Coverage'),
       ('Geography', 'Total Waterway Coverage value'),
       ('Geography', 'Total Border Coverage'),
       ('Geography', 'Total Border Coverage value')], dtype=object)

In [241]:
df.columns = ["_".join(list(map(str,column))) for column in df.columns.values]

In [244]:
df.head()

,2020 ranking_Military Strength,2020 ranking_Military Strength Power Index,Airforce Strength_Aircraft Strength,Airforce Strength_Aircraft Strength value,Airforce Strength_Fighter/Interceptor Strength,Airforce Strength_Fighter/Interceptor Strength value,Airforce Strength_Attack Aircraft Strength,Airforce Strength_Attack Aircraft Strength value,Airforce Strength_Transport Aircraft Fleet Strength,Airforce Strength_Transport Aircraft Fleet Strength value,Airforce Strength_Trainer Aircraft Fleet,Airforce Strength_Trainer Aircraft Fleet value,Airforce Strength_Helicopter Fleet Strength,Airforce Strength_Helicopter Fleet Strength value,Airforce Strength_Attack Helicopter Fleet Strength,Airforce Strength_Attack Helicopter Fleet Strength value,Land Strength_Tank Strength,Land Strength_Tank Strength value,Land Strength_AFV/APC Strength,Land Strength_AFV/APC Strength value,Land Strength_Self-Propelled Artillery Strength,Land Strength_Self-Propelled Artillery Strength value,Land Strength_Towed Artillery Strength,Land Strength_Towed Artillery Strength value,Land Strength_Rocket Projector Strength,Land Strength_Rocket Projector Strength value,Navy Strength_Navy Fleet Strengths,Navy Strength_Navy Fleet Strengths value,Navy Strength_Aircraft Carrier Fleet Strength,Navy Strength_Aircraft Carrier Fleet Strength value,Navy Strength_Submarine Fleet Strength,Navy Strength_Submarine Fleet Strength value,Navy Strength_Destroyer Fleet Strength,Navy Strength_Destroyer Fleet Strength value,Navy Strength_Frigate Fleet Strength,Navy Strength_Frigate Fleet Strength value,Finances_defense spending budget,Finances_defense spending budget value,Finances_External Debt,Finances_External Debt value,Logistics_Airport Totals,Logistics_Airport Totals value,Natural resources_Oil Production,Natural resources_Oil Production value,Natural resources_Oil Consumption,Natural resources_Oil Consumption value,Natural resources_Proven Oil Reserves,Natural resources_Proven Oil Reserves value,Manpower_Available Manpower,Manpower_Available Manpower value,Manpower_Total Population,Manpower_Total Population value,Geography_Total Square Land Area,Geography_Total Square Land Area value,Geography_Total Coastline Coverage,Geography_Total Coastline Coverage value,Geography_Total Waterway Coverage,Geography_Total Waterway Coverage value,Geography_Total Border Coverage,Geography_Total Border Coverage value
0,Afghanistan,1.3444,Afghanistan,260,Afghanistan,0,Afghanistan,25,Afghanistan,30,Afghanistan,0,Afghanistan,187,Afghanistan,0,Afghanistan,0,Afghanistan,1062,Afghanistan,0,Afghanistan,176,Afghanistan,50,Afghanistan,0.0,Afghanistan,0.0,Afghanistan,0.0,Afghanistan,0.0,Afghanistan,0.0,Afghanistan,"12,00,00,00,000",Afghanistan,"2,84,00,00,000",Afghanistan,43,Afghanistan,0,Afghanistan,5500,Afghanistan,0,Afghanistan,"1,43,25,743",Afghanistan,"3,49,40,837",Afghanistan,"6,52,230",Afghanistan,0,Afghanistan,1200,Afghanistan,5987.0
1,Albania,2.3137,Albania,19,Albania,0,Albania,0,Albania,0,Albania,0,Albania,19,Albania,0,Albania,0,Albania,467,Albania,0,Albania,0,Albania,0,Albania,38.0,Albania,0.0,Albania,0.0,Albania,0.0,Albania,0.0,Albania,"25,00,00,000",Albania,"9,50,50,00,000",Albania,4,Albania,16000,Albania,42500,Albania,"16,83,00,000",Albania,"15,19,438",Albania,"30,57,220",Albania,28748,Albania,362,Albania,41,Albania,691.0
2,Algeria,0.4659,Algeria,551,Algeria,103,Algeria,22,Algeria,59,Algeria,87,Algeria,257,Algeria,45,Algeria,880,Algeria,7361,Algeria,320,Algeria,240,Algeria,316,Algeria,201.0,Algeria,0.0,Algeria,6.0,Algeria,0.0,Algeria,5.0,Algeria,"13,00,00,00,000",Algeria,"6,26,00,00,000",Algeria,157,Algeria,"13,06,000",Algeria,"3,25,000",Algeria,"12,20,00,00,000",Algeria,"2,07,41,263",Algeria,"4,16,57,488",Algeria,"23,81,741",Algeria,998,Algeria,0,Algeria,6734.0
3,Angola,0.8379,Angola,295,Angola,72,Angola,18,Angola,30,Angola,47,Angola,126,Angola,15,Angola,379,Angola,595,Angola,28,Angola,357,Angola,115,Angola,57.0,Angola,0.0,Angola,0.0,Angola,0.0,Angola,0.0,Angola,"7,00,00,00,000",Angola,"42,08,00,00,000",Angola,176,Angola,"16,66,000",Angola,82300,Angola,"8,27,30,00,000",Angola,"62,44,205",Angola,"3,03,55,880",Angola,"12,46,700",Angola,1600,Angola,1300,Angola,5369.0
4,Argentina,0.6521,Argentina,227,Argentina,24,Argentina,7,Argentina,9,Argentina,64,Argentina,100,Argentina,0,Argentina,370,Argentina,739,Argentina,83,Argentina,172,Argentina,26,Argentina,49.0,Argentina,0.0,Argentina,2.0,Argentina,4.0,Argentina,0.0,Argentina,"4,20,00,00,000",Argentina,"2,14,90,00,00,000",Argentina,1138,Argentina,"4,79,400",Argentina,"6,85,000",Argentina,"2,18,50,00,000",Argentina,"2,01,79,430",Argentina,"4,46,94,198",Argentina,"27,80,400",Argentina,4989,Argentina,11000,Argentina,11968.0

## Detect and drop duplicated columns

In [247]:
value_cols = [column[0] for column in df.columns.str.findall(".*value") if  len(column) > 0 ]

In [249]:
print(value_cols)

['Airforce Strength_Aircraft Strength value', 'Airforce Strength_Fighter/Interceptor Strength value', 'Airforce Strength_Attack Aircraft Strength value', 'Airforce Strength_Transport Aircraft Fleet Strength value', 'Airforce Strength_Trainer Aircraft Fleet value', 'Airforce Strength_Helicopter Fleet Strength value', 'Airforce Strength_Attack Helicopter Fleet Strength value', 'Land Strength_Tank Strength value', 'Land Strength_AFV/APC Strength value', 'Land Strength_Self-Propelled Artillery Strength value', 'Land Strength_Towed Artillery Strength value', 'Land Strength_Rocket Projector Strength value', 'Navy Strength_Navy Fleet Strengths value', 'Navy Strength_Aircraft Carrier Fleet Strength value', 'Navy Strength_Submarine Fleet Strength value', 'Navy Strength_Destroyer Fleet Strength value', 'Navy Strength_Frigate Fleet Strength value', 'Finances_defense spending budget value', 'Finances_External Debt value', 'Logistics_Airport Totals value', 'Natural resources_Oil Production value', 'Natural resources_Oil Consumption value', 'Natural resources_Proven Oil Reserves value', 'Manpower_Available Manpower value', 'Manpower_Total Population value', 'Geography_Total Square Land Area value', 'Geography_Total Coastline Coverage value', 'Geography_Total Waterway Coverage value', 'Geography_Total Border Coverage value']

In [255]:
df2 = df.copy()

In [257]:
df = df2[value_cols]
df.insert(0, "country", df2["2020 ranking_Military Strength"])
df.insert(1, "Military Strength Power Index", df2["2020 ranking_Military Strength Power Index"])

df.head()

,country,Military Strength Power Index,Airforce Strength_Aircraft Strength value,Airforce Strength_Fighter/Interceptor Strength value,Airforce Strength_Attack Aircraft Strength value,Airforce Strength_Transport Aircraft Fleet Strength value,Airforce Strength_Trainer Aircraft Fleet value,Airforce Strength_Helicopter Fleet Strength value,Airforce Strength_Attack Helicopter Fleet Strength value,Land Strength_Tank Strength value,Land Strength_AFV/APC Strength value,Land Strength_Self-Propelled Artillery Strength value,Land Strength_Towed Artillery Strength value,Land Strength_Rocket Projector Strength value,Navy Strength_Navy Fleet Strengths value,Navy Strength_Aircraft Carrier Fleet Strength value,Navy Strength_Submarine Fleet Strength value,Navy Strength_Destroyer Fleet Strength value,Navy Strength_Frigate Fleet Strength value,Finances_defense spending budget value,Finances_External Debt value,Logistics_Airport Totals value,Natural resources_Oil Production value,Natural resources_Oil Consumption value,Natural resources_Proven Oil Reserves value,Manpower_Available Manpower value,Manpower_Total Population value,Geography_Total Square Land Area value,Geography_Total Coastline Coverage value,Geography_Total Waterway Coverage value,Geography_Total Border Coverage value
0,Afghanistan,1.3444,260,0,25,30,0,187,0,0,1062,0,176,50,0.0,0.0,0.0,0.0,0.0,"12,00,00,00,000","2,84,00,00,000",43,0,5500,0,"1,43,25,743","3,49,40,837","6,52,230",0,1200,5987.0
1,Albania,2.3137,19,0,0,0,0,19,0,0,467,0,0,0,38.0,0.0,0.0,0.0,0.0,"25,00,00,000","9,50,50,00,000",4,16000,42500,"16,83,00,000","15,19,438","30,57,220",28748,362,41,691.0
2,Algeria,0.4659,551,103,22,59,87,257,45,880,7361,320,240,316,201.0,0.0,6.0,0.0,5.0,"13,00,00,00,000","6,26,00,00,000",157,"13,06,000","3,25,000","12,20,00,00,000","2,07,41,263","4,16,57,488","23,81,741",998,0,6734.0
3,Angola,0.8379,295,72,18,30,47,126,15,379,595,28,357,115,57.0,0.0,0.0,0.0,0.0,"7,00,00,00,000","42,08,00,00,000",176,"16,66,000",82300,"8,27,30,00,000","62,44,205","3,03,55,880","12,46,700",1600,1300,5369.0
4,Argentina,0.6521,227,24,7,9,64,100,0,370,739,83,172,26,49.0,0.0,2.0,4.0,0.0,"4,20,00,00,000","2,14,90,00,00,000",1138,"4,79,400","6,85,000","2,18,50,00,000","2,01,79,430","4,46,94,198","27,80,400",4989,11000,11968.0

## Check for missing values

In [261]:
df.isnull().sum().sort_values(ascending=False)[:10]

Geography_Total Coastline Coverage value                    29
Navy Strength_Aircraft Carrier Fleet Strength value         23
Navy Strength_Frigate Fleet Strength value                  23
Navy Strength_Destroyer Fleet Strength value                23
Navy Strength_Submarine Fleet Strength value                23
Navy Strength_Navy Fleet Strengths value                    14
Geography_Total Border Coverage value                        9
Airforce Strength_Helicopter Fleet Strength value            0
Airforce Strength_Attack Helicopter Fleet Strength value     0
Geography_Total Waterway Coverage value                      0
dtype: int64

In [265]:
df.isnull().melt(value_name="missing")

                                   variable  missing
0                                   country    False
1                                   country    False
2                                   country    False
3                                   country    False
4                                   country    False
...                                     ...      ...
4273  Geography_Total Border Coverage value    False
4274  Geography_Total Border Coverage value    False
4275  Geography_Total Border Coverage value    False
4276  Geography_Total Border Coverage value    False
4277  Geography_Total Border Coverage value    False

[4278 rows x 2 columns]

In [ ]:
plt.figure(figsize = (4, 6))
sns.

## Deal with missing values 
* Hint-1, use wikipedia to fill in missing values ​​comparing with similar countries
* Hint-2, Georeferences of countries can help you

## Fix the dtypes

## Drop the features that not affect military power
* Hint-1,  Georeferences not proper features

## Visualy inspect the some features

## Decriptive statistics

# Data Preprocessing

# Modelling

## Hopkins Test 
#### Assess the clusterability of a dataset. A score between 0 and 1, a score around 0.5 express no clusterability, a score tending to 1 express an uniform distrubution so clustering can't be useful and  0 express  not an uniform distrubution hence clusterering can be useful.

## 1. Clustering with K-means

### Elbow Method 
### We use this method to find optimal k value by looking up to break point of graph.

### Silhoutte Analysis

### Model Building and label visualisation

### Evaluate

## 2. Hierarchical Clustering

### Dendogram

### Model Building and label visualisation

### Evaluate